image: registry.gitlab.com/materials-modeling/icet:latest

stages:
  - build
  - test
  - deploy
  - pypi
  - conda

before_script:
  - INSTDIR=$PWD/opt/lib/python
  - export PYTHONPATH=$INSTDIR:$PYTHONPATH

build:
  stage: build
  tags:
    - macos
  script:
    - mkdir -p $INSTDIR
    - python3 ./setup.py install --home=$PWD/opt
    - python3 setup.py sdist
  artifacts:
    expire_in: 14 days
    paths:
      - opt/
      - dist/

tests:
  stage: test
  tags:
    - macos
  script:
    - printenv
#    - xdoctest icet
    - xdoctest mchammer
    - coverage run tests/main.py
    - coverage report -m
    - coverage html
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    expire_in: 14 days
    paths:
      - htmlcov/
      - opt/
      - dist/